FROM golang:latest

ENV SERVICE_ENV production

RUN mkdir -p -m 775 /workspace/golang_backend
RUN go get -u bitbucket.org/liamstask/goose/cmd/goose

WORKDIR /workspace/golang_backend

ADD ./ /workspace/golang_backend

RUN ["go", "build"]
CMD ["/workspace/golang_backend/main.go"]
